services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin # mật khẩu admin
        ports:
            - '3000:3000'
        depends_on:
            - prometheus
